import Head from "next/head";
import { useAppSelector } from "@/customHooks/hooks";


export default function Home() {
  const { token } = useAppSelector((state) => state.user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Hi</p>
    </>
  );
}
